# Generated by Django 3.2 on 2021-05-18 14:24

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tech_school_app', '0005_auto_20210518_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='InSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Вопрос в опросе',
                'verbose_name_plural': 'Вопросы в опросах',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст вопроса')),
                ('survey_type', models.CharField(choices=[('0', 'CLEI'), ('1', 'Big5'), ('2', '360')], max_length=1, verbose_name='Тип опроса')),
                ('options', jsonfield.fields.JSONField(default=dict, verbose_name='Варианты ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[('t', 'teacher'), ('s', 'student')], default='s', max_length=1, verbose_name='Кому предназначен')),
                ('is_active', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=1, verbose_name='Активен ли')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.group', verbose_name='Группа')),
                ('questions', models.ManyToManyField(through='survey_app.InSurvey', to='survey_app.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='SurveyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Генерируемый код опроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Код опроса',
                'verbose_name_plural': 'Коды опросов',
            },
        ),
        migrations.AddField(
            model_name='insurvey',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='insurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', jsonfield.fields.JSONField(default=dict, verbose_name='Ответы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='Студент')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
