# Generated by Django 3.2 on 2021-05-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Генерируемый уникальный код опроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Код опроса',
                'verbose_name_plural': 'Коды опросов',
            },
        ),
        migrations.DeleteModel(
            name='SurveyCode',
        ),
    ]
