# Generated by Django 3.2 on 2021-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0002_auto_20210524_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
