# Generated by Django 3.2 on 2021-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='number_in_survey',
            field=models.IntegerField(default=1, verbose_name='Номер в опроснике'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='options_values',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=1, verbose_name='Варианты ответа'),
            preserve_default=False,
        ),
    ]
