# Generated by Django 3.2 on 2021-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0005_auto_20210524_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_values', models.CharField(max_length=1, verbose_name='Варианты ответа')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='options_values',
        ),
    ]
