# Generated by Django 3.2 on 2021-05-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_alter_options_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='options_values',
            field=models.IntegerField(verbose_name='Варианты ответа'),
        ),
    ]
