# Generated by Django 3.2 on 2021-05-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0008_alter_options_options_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
    ]
