# Generated by Django 3.2 on 2021-05-24 19:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0009_delete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=jsonfield.fields.JSONField(default={'1': 1, '2': 2, '3': 3, '4': 4, '5': 5}, verbose_name='Варианты ответа'),
        ),
    ]
