# Generated by Django 3.2 on 2021-05-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0010_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
