# Generated by Django 3.2 on 2021-05-25 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0011_remove_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=1, max_length=1, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey_app.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
