# Generated by Django 3.2 on 2021-05-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0005_auto_20210518_1424'),
        ('survey_app', '0012_auto_20210525_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyslug',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='Студент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyslug',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='Сотрудник'),
        ),
    ]
