# Generated by Django 3.2 on 2021-05-25 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0005_auto_20210518_1424'),
        ('survey_app', '0013_auto_20210525_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.question', verbose_name='Вопрос')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='Студент')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Ответ преподавателя',
                'verbose_name_plural': 'Ответы преподавателей',
            },
        ),
        migrations.CreateModel(
            name='SurveySlugStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Генерируемый уникальный код опроса')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='Студент')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Код опроса для студентов',
                'verbose_name_plural': 'Коды опросов для студентов',
            },
        ),
        migrations.CreateModel(
            name='SurveySlugWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Генерируемый уникальный код опроса')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='Студент')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='Опрос')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Код опроса для преподавателей',
                'verbose_name_plural': 'Коды опросов для преподавателей',
            },
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerStudent',
        ),
        migrations.AlterModelOptions(
            name='answerstudent',
            options={'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Ответы студентов'},
        ),
        migrations.DeleteModel(
            name='SurveySlug',
        ),
    ]
