# Generated by Django 3.2 on 2021-05-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0015_alter_answerstudent_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerworker',
            name='answer',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1, verbose_name='Ответ'),
        ),
    ]
