# Generated by Django 3.2 on 2021-05-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0016_alter_answerworker_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
    ]
