# Generated by Django 3.2 on 2021-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0019_alter_studentpkandslug_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpkandslug',
            name='title',
            field=models.SlugField(max_length=10),
        ),
    ]
