# Generated by Django 3.2 on 2021-05-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0012_auto_20210526_1024'),
        ('survey_app', '0020_alter_studentpkandslug_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpkandslug',
            options={'verbose_name': 'Код опроса', 'verbose_name_plural': 'Коды опросов'},
        ),
        migrations.RemoveField(
            model_name='studentpkandslug',
            name='title',
        ),
        migrations.AddField(
            model_name='studentpkandslug',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='студент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentpkandslug',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=10, verbose_name='персональный код'),
        ),
    ]
