# Generated by Django 3.2 on 2021-05-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0012_auto_20210526_1024'),
        ('survey_app', '0021_auto_20210526_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpkandslug',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='преподаватель'),
        ),
    ]
