# Generated by Django 3.2 on 2021-05-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0012_auto_20210526_1024'),
        ('survey_app', '0022_studentpkandslug_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpkandslug',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='преподаватель'),
        ),
    ]
