# Generated by Django 3.2 on 2021-05-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0023_alter_studentpkandslug_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyslugworker',
            name='student',
        ),
        migrations.RemoveField(
            model_name='surveyslugworker',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyslugworker',
            name='worker',
        ),
        migrations.AddField(
            model_name='studentpkandslug',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='опрос'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SurveySlugStudent',
        ),
        migrations.DeleteModel(
            name='SurveySlugWorker',
        ),
    ]
