# Generated by Django 3.2 on 2021-05-27 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0013_auto_20210526_1302'),
        ('survey_app', '0024_auto_20210526_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.question', verbose_name='Вопрос')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='Студент')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.RemoveField(
            model_name='answerworker',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answerworker',
            name='student',
        ),
        migrations.RemoveField(
            model_name='answerworker',
            name='worker',
        ),
        migrations.DeleteModel(
            name='AnswerStudent',
        ),
        migrations.DeleteModel(
            name='AnswerWorker',
        ),
    ]
