# Generated by Django 3.2 on 2021-05-27 04:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0013_auto_20210526_1302'),
        ('survey_app', '0025_auto_20210527_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', jsonfield.fields.JSONField(blank='True', null='True', verbose_name='Ответы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='студент')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='опрос')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
