# Generated by Django 3.2 on 2021-05-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0026_surveyanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ 1 вариат', 'verbose_name_plural': 'Ответы 1 вариант'},
        ),
        migrations.AlterModelOptions(
            name='surveyanswer',
            options={'verbose_name': 'Ответ 2 вариант', 'verbose_name_plural': 'Ответы 2 вариант'},
        ),
    ]
