# Generated by Django 3.2 on 2021-05-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0028_testfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfrom',
            name='testfield',
            field=models.CharField(choices=[('1', 1), ('2', 2)], max_length=1),
        ),
    ]
