# Generated by Django 3.2 on 2021-05-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0030_auto_20210527_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfrom',
            name='testfield',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
