# Generated by Django 3.2 on 2021-05-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0013_auto_20210526_1302'),
        ('survey_app', '0031_auto_20210528_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.student', verbose_name='студент')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey', verbose_name='опрос')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.worker', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'Кому',
                'verbose_name_plural': 'Кому',
            },
        ),
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=15, verbose_name='персональный код')),
                ('link', models.SlugField(default='', editable=False, verbose_name='персональная ссылка')),
                ('surveywho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.surveywho', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1, verbose_name='ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.question', verbose_name='вопрос')),
                ('surveywho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.surveywho', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
