# Generated by Django 3.2 on 2021-05-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0032_answer_slug_surveywho'),
    ]

    operations = [
        migrations.AddField(
            model_name='slug',
            name='if_sent',
            field=models.CharField(choices=[('0', 'не отправлено'), ('1', 'отправлено')], default='0', max_length=1, verbose_name='cтатус отправления'),
        ),
        migrations.AlterField(
            model_name='slug',
            name='link',
            field=models.CharField(blank=True, default='', editable=False, max_length=25, verbose_name='персональная ссылка'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='who',
            field=models.CharField(choices=[('t', 'сотруднику'), ('s', 'учащемуся')], default='s', max_length=1, verbose_name='Кому предназначен'),
        ),
    ]
