# Generated by Django 3.2 on 2021-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0034_auto_20210530_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slug',
            name='link',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, verbose_name='персональная ссылка'),
        ),
    ]
