# Generated by Django 3.2 on 2021-05-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0035_alter_slug_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='testfrom',
            name='pers',
        ),
        migrations.AlterField(
            model_name='slug',
            name='if_sent',
            field=models.CharField(choices=[('0', 'не отправлено'), ('1', 'отправлено')], default='0', max_length=1, verbose_name='Cтатус отправления'),
        ),
        migrations.AlterField(
            model_name='slug',
            name='surveywho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.surveywho', verbose_name='Опрос'),
        ),
        migrations.DeleteModel(
            name='StudentPkAndSlug',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
        migrations.DeleteModel(
            name='TestFrom',
        ),
    ]
