# Generated by Django 3.2 on 2021-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0036_auto_20210530_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_active',
            field=models.CharField(choices=[('0', 'не активен'), ('1', 'активен')], default='1', max_length=1, verbose_name='Активен ли'),
        ),
    ]
