# Generated by Django 3.2 on 2021-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0002_auto_20210516_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='edu_level',
            field=models.CharField(choices=[('0', 'рабочие и учащиеся Технической школы'), ('1', 'руководители среднего звена, специалисты, служащие'), ('2', 'руководители подразделений')], default='1', max_length=1, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='salarynorm',
            name='edu_level',
            field=models.CharField(choices=[('0', 'рабочие и учащиеся Технической школы'), ('1', 'руководители среднего звена, специалисты, служащие'), ('2', 'руководители подразделений')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='workingdates',
            name='in_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
