# Generated by Django 3.2 on 2021-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0003_auto_20210516_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='next_training',
            field=models.DateField(verbose_name='Следующее обучение'),
        ),
    ]
