# Generated by Django 3.2 on 2021-05-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0004_auto_20210517_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurvey',
            name='question',
        ),
        migrations.RemoveField(
            model_name='insurvey',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='group',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveycode',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='InSurvey',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyCode',
        ),
    ]
