# Generated by Django 3.2 on 2021-05-25 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech_school_app', '0005_auto_20210518_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Планы. Календарный план', 'verbose_name_plural': 'Планы. Календарные планы'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-id'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='cpdetails',
            options={'verbose_name': 'Планы. Детали календарного плана', 'verbose_name_plural': 'Планы. Детали календарных планов'},
        ),
        migrations.AlterModelOptions(
            name='incp',
            options={'verbose_name': 'Планы. Элемент календарного плана', 'verbose_name_plural': 'Планы. Элементы календарных планов'},
        ),
        migrations.AlterModelOptions(
            name='intp',
            options={'verbose_name': 'Планы. Элемент учебного плана', 'verbose_name_plural': 'Планы. Элементы учебных планов'},
        ),
        migrations.AlterModelOptions(
            name='tpdetails',
            options={'verbose_name': 'Планы. Детали учебного плана', 'verbose_name_plural': 'Планы. Детали учебных планов'},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'verbose_name': 'Планы. Учебный план', 'verbose_name_plural': 'Планы. Учебные планы'},
        ),
        migrations.RemoveField(
            model_name='draftintp',
            name='draft_tp',
        ),
        migrations.RemoveField(
            model_name='draftintp',
            name='group',
        ),
        migrations.RemoveField(
            model_name='draftth',
            name='date',
        ),
        migrations.RemoveField(
            model_name='draftth',
            name='group',
        ),
        migrations.RemoveField(
            model_name='draftth',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='draftth',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='draftth',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='draftth',
            name='time_type',
        ),
        migrations.RemoveField(
            model_name='drafttp',
            name='calendarplan',
        ),
        migrations.RemoveField(
            model_name='drafttp',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='drafttp',
            name='status',
        ),
        migrations.RemoveField(
            model_name='drafttp',
            name='year',
        ),
        migrations.RemoveField(
            model_name='drafttpdetails',
            name='draft_intp',
        ),
        migrations.RemoveField(
            model_name='drafttpdetails',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='drafttpdetails',
            name='month',
        ),
        migrations.AddField(
            model_name='draftintp',
            name='content',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='draftintp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draftintp',
            name='who_changed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draftth',
            name='content',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='draftth',
            name='who_changed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drafttp',
            name='content',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='drafttp',
            name='who_changed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drafttpdetails',
            name='content',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='drafttpdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drafttpdetails',
            name='who_changed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draftth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drafttp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
    ]
