# Generated by Django 3.2 on 2021-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0006_auto_20210525_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafttp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
