# Generated by Django 3.2 on 2021-05-26 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech_school_app', '0008_trainingplan_who_changed_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='intp',
            name='who_changed_last',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
        migrations.AddField(
            model_name='tpdetails',
            name='who_changed_last',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
        migrations.AddField(
            model_name='traininghours',
            name='who_changed_last',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='who_changed_last',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
    ]
