# Generated by Django 3.2 on 2021-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0009_auto_20210526_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='intp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='tpdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
