# Generated by Django 3.2 on 2021-05-26 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech_school_app', '0011_auto_20210526_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Календарный план', 'verbose_name_plural': 'Календарные планы'},
        ),
        migrations.AlterModelOptions(
            name='cpdetails',
            options={'verbose_name': 'Календарный план (детали)', 'verbose_name_plural': 'Календарные планы (детали)'},
        ),
        migrations.AlterModelOptions(
            name='draftintp',
            options={'verbose_name': 'Версия элемента учебного плана', 'verbose_name_plural': 'Версии элементов учебных планов'},
        ),
        migrations.AlterModelOptions(
            name='draftth',
            options={'verbose_name': 'Версия учёта часов', 'verbose_name_plural': 'Версии учёта часов'},
        ),
        migrations.AlterModelOptions(
            name='drafttp',
            options={'verbose_name': 'Версия учебного плана', 'verbose_name_plural': 'Версии учебных планов'},
        ),
        migrations.AlterModelOptions(
            name='drafttpdetails',
            options={'verbose_name': 'Версия деталей учебного плана', 'verbose_name_plural': 'Версии деталей учебных планов'},
        ),
        migrations.AlterModelOptions(
            name='incp',
            options={'verbose_name': 'Календарный план (элемент)', 'verbose_name_plural': 'Календарные планы (элементы)'},
        ),
        migrations.AlterModelOptions(
            name='intp',
            options={'verbose_name': 'Учебный план (элемент)', 'verbose_name_plural': 'Учебные планы (элементы)'},
        ),
        migrations.AlterModelOptions(
            name='tpdetails',
            options={'verbose_name': 'Учебный план (детали)', 'verbose_name_plural': 'Учебные планы (детали)'},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterField(
            model_name='draftintp',
            name='who_changed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
        migrations.AlterField(
            model_name='draftth',
            name='who_changed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
        migrations.AlterField(
            model_name='drafttp',
            name='who_changed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
        migrations.AlterField(
            model_name='drafttpdetails',
            name='who_changed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Последний редактировал'),
        ),
    ]
