# Generated by Django 3.2 on 2021-05-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0012_auto_20210526_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarynorm',
            name='edu_level',
        ),
        migrations.RemoveField(
            model_name='salarynorm',
            name='salary_level',
        ),
        migrations.RemoveField(
            model_name='salarynorm',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='salarynorm',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='salarynorm',
            name='education_level',
            field=models.CharField(choices=[('0', 'Высшее'), ('1', 'СПО'), ('2', 'Среднее Общее')], default='0', max_length=1, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='salarynorm',
            name='if_valid',
            field=models.CharField(choices=[('0', 'not valid'), ('1', 'valid')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='salarynorm',
            name='students',
            field=models.CharField(choices=[('0', 'рабочие и учащиеся Технической школы'), ('1', 'руководители среднего звена, специалисты, служащие'), ('2', 'руководители подразделений')], default='0', max_length=1),
        ),
    ]
