# Generated by Django 3.2 on 2021-05-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0013_auto_20210526_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolarshipnorm',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='scolarshipnorm',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='scolarshipnorm',
            name='description',
            field=models.CharField(blank=True, max_length=400, verbose_name='Описание из документа'),
        ),
        migrations.AddField(
            model_name='scolarshipnorm',
            name='if_valid',
            field=models.CharField(choices=[('0', 'not valid'), ('1', 'valid')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='license',
            name='image',
            field=models.ImageField(upload_to='media/licenses', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='amount',
            field=models.IntegerField(verbose_name='Количество руб./мес.'),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='higher',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Верхняя граница балла'),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='lower',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Нижняя граница балла'),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='period',
            field=models.CharField(choices=[('t', 'theory'), ('p', 'practice')], default='t', max_length=1, verbose_name='Период обучения'),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_school_app.program', verbose_name='Программа'),
        ),
    ]
