# Generated by Django 3.2 on 2021-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0014_auto_20210530_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfochanges',
            options={'verbose_name': 'Изменение в персональных данных', 'verbose_name_plural': 'Изменения в персональных данных'},
        ),
        migrations.AlterModelOptions(
            name='workerchanges',
            options={'verbose_name': 'Изменение в данных сотрудника', 'verbose_name_plural': 'Изменения в данных сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='workingdates',
            options={'verbose_name': 'День в календаре', 'verbose_name_plural': 'Производственный календарь'},
        ),
        migrations.RemoveField(
            model_name='license',
            name='image',
        ),
        migrations.AddField(
            model_name='hoursnorm',
            name='period',
            field=models.CharField(choices=[('y', 'год'), ('m', 'месяц'), ('d', 'день')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='license',
            name='scan',
            field=models.FileField(default=1, upload_to='media/licenses', verbose_name='Скан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpdetails',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default='1', max_length=2, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='attendance',
            field=models.CharField(blank=True, choices=[('0', 'пропустил'), ('1', 'посетил')], default='0', max_length=1, verbose_name='Посещение'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('g', 'оценка'), ('a', 'посещение')], default='g', max_length=1, verbose_name='Оценка / Посещение'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('0', 'закрыта'), ('1', 'обучение продолжается')], default='1', max_length=1, verbose_name='Статус группы'),
        ),
        migrations.AlterField(
            model_name='license',
            name='relevance',
            field=models.CharField(choices=[('0', 'нерелевантная'), ('1', 'релевантная')], default='1', max_length=1, verbose_name='Релевантность'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='importance',
            field=models.CharField(choices=[('0', 'низкая'), ('1', 'нейтральная'), ('2', 'высокая')], default='1', max_length=1, verbose_name='Степень важности'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('0', 'новое'), ('1', 'открытое')], default='0', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='salarynorm',
            name='if_valid',
            field=models.CharField(choices=[('0', 'не валидна'), ('1', 'валидна')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='if_valid',
            field=models.CharField(choices=[('0', 'не валидна'), ('1', 'валидна')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='period',
            field=models.CharField(choices=[('t', 'теория'), ('p', 'практика')], default='t', max_length=1, verbose_name='Период обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_status',
            field=models.CharField(choices=[('0', 'не обучается'), ('1', 'обучается')], default='1', max_length=1, verbose_name='Статус обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='from_staff',
            field=models.CharField(choices=[('0', 'не из персонала'), ('1', 'из персонала')], default='0', max_length=1, verbose_name='Из персонала'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.CharField(choices=[('0', 'неактивен'), ('1', 'активен')], default='0', max_length=1, verbose_name='Активен ли пользователь'),
        ),
        migrations.AlterField(
            model_name='tpdetails',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], default='1', max_length=2, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='traininghours',
            name='time_type',
            field=models.CharField(choices=[('w', 'рабочее'), ('p', 'личное')], default='w', max_length=1, verbose_name='Тип времени'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='relevance',
            field=models.CharField(choices=[('0', 'черновик'), ('1', 'утверждённый')], default='0', max_length=1, verbose_name='Релевантность'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='status',
            field=models.CharField(choices=[('0', 'активен'), ('1', 'неактивен')], default='1', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='available',
            field=models.CharField(choices=[('0', 'недоступен'), ('1', 'доступен')], default='0', max_length=1, verbose_name='Доступен для преподавания'),
        ),
    ]
