# Generated by Django 3.2 on 2021-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0015_auto_20210611_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='education_date',
        ),
        migrations.AddField(
            model_name='license',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата из документа'),
        ),
    ]
