# Generated by Django 3.2 on 2021-06-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0016_auto_20210611_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Телефон'),
        ),
    ]
