# Generated by Django 3.2 on 2021-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_school_app', '0017_auto_20210611_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpdetails',
            options={'ordering': ['-id'], 'verbose_name': 'Календарный план (детали)', 'verbose_name_plural': 'Календарные планы (детали)'},
        ),
        migrations.AlterModelOptions(
            name='incp',
            options={'ordering': ['-id'], 'verbose_name': 'Календарный план (элемент)', 'verbose_name_plural': 'Календарные планы (элементы)'},
        ),
        migrations.AlterModelOptions(
            name='intp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Учебный план (элемент)', 'verbose_name_plural': 'Учебные планы (элементы)'},
        ),
        migrations.AlterModelOptions(
            name='tpdetails',
            options={'ordering': ['-created_at'], 'verbose_name': 'Учебный план (детали)', 'verbose_name_plural': 'Учебные планы (детали)'},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='workingdates',
            options={'ordering': ['-date'], 'verbose_name': 'День в календаре', 'verbose_name_plural': 'Производственный календарь'},
        ),
        migrations.AlterField(
            model_name='calendarplan',
            name='relevance',
            field=models.CharField(choices=[('0', 'нерелевантный'), ('1', 'релевантный')], default='1', max_length=1, verbose_name='Релевантность'),
        ),
        migrations.AlterField(
            model_name='salarynorm',
            name='amount',
            field=models.IntegerField(verbose_name='Тариф руб./ч.'),
        ),
        migrations.AlterField(
            model_name='salarynorm',
            name='if_valid',
            field=models.CharField(choices=[('0', 'не валидна'), ('1', 'валидна')], default='1', max_length=1, verbose_name='Валидность'),
        ),
        migrations.AlterField(
            model_name='salarynorm',
            name='students',
            field=models.CharField(choices=[('0', 'рабочие и учащиеся Технической школы'), ('1', 'руководители среднего звена, специалисты, служащие'), ('2', 'руководители подразделений')], default='0', max_length=1, verbose_name='Контингент учащихся'),
        ),
        migrations.AlterField(
            model_name='salarynorm',
            name='time_type',
            field=models.CharField(choices=[('w', 'рабочее'), ('p', 'личное')], default='w', max_length=1, verbose_name='Тип времени'),
        ),
        migrations.AlterField(
            model_name='scolarshipnorm',
            name='if_valid',
            field=models.CharField(choices=[('0', 'не валидна'), ('1', 'валидна')], default='1', max_length=1, verbose_name='Валидность'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='status',
            field=models.CharField(choices=[('0', 'неактивен'), ('1', 'активен')], default='1', max_length=1, verbose_name='Статус'),
        ),
    ]
